set nocompatible
set backspace=indent,eol,start
set history=50
set ruler
set showcmd
set incsearch
syntax enable
set ffs=unix
set shiftwidth=4
set tabstop=4
set expandtab
"set autoindent
color delek
"let g:solarized_termcolors=256
"set background=dark
"set background=light
"colorscheme solarized
